# Mongo Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: eagleeye
spec:
  selector:
    name: mongo-deploy
  #externalIPs:
  #- 10.194.188.111
  ports:
  - port: 27017
    targetPort: 27017
