# Scheduler
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer-deploy
  namespace: eagleeye
  labels:
    name: visualizer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: visualizer-deploy
  template:
    metadata:
      name: visualizer-deploy
      labels:
        name: visualizer-deploy
#      annotations:
#        k8s.v1.cni.cncf.io/networks: '[
#          {
#            "name": "data-net-app",
#            "namespace": "mec-app",
#            "ips": [ "10.194.188.117/24" ]
#          }
#        ]'

    spec:
      volumes:
        - name: visualizer-config
          configMap:
            name: visualizer-configmap
            items:
            - key: "visualizer.conf"
              path: "visualizer.conf"
            - key: "site.conf"
              path: "site.conf"
      containers:
        - name: visualizer-deploy
          #image: 5g-dive/eagleeye/scheduler-service:1.0
          image: timwilliam/eagleeye.visualizer:2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 554
          volumeMounts:
            - name: visualizer-config
              mountPath: "/conf/visualizer"
              readOnly: false