apiVersion: v1
kind: ConfigMap
metadata:
  name: visualizer-configmap
  namespace: eagleeye
data:
  visualizer.conf: |
    [general]
    include = /conf/visualizer/site.conf

    [redis]
    hostname=localhost
    port=6379
    password=
    db=0

    [eagleeye:api]
    node=http://localhost:8080/api/nodes
    latency = http://localhost:8080/api/latency

    [pubsub:channel]
    scheduler=scheduler

    [zmq]
    sender_host=127.0.0.1
    sender_port=5550

    [stream:config]
    mode=rtsp
    is_raw=0
    is_forced_plot=0
    protocol=rtsp
    host=localhost
    path=ee-raw
    fps=30
    width=1920
    height=1080
    delay=33
    drone_id=1
    gps_key_prefix=gps-data-
    window_width=1920
    window_height=1080

    [stream:gps]
    mode=offline
    schema=http
    host=10.194.188.105
    port=36002
    path=FlySocketWCF
    num_drones=2
  site.conf: |
    [redis]
    hostname=10.194.188.110
    password =

    [zmq]
    sender_host=10.194.188.116
    sender_port=5550

    [eagleeye:api]
    node=http://10.194.188.112:8080/api/nodes
    latency = http://10.194.188.112:8080/api/latency

    [stream:config]
    width=1920
    height=1080

    # This is the maximum waiting time to receive Plot info (including PiH BBox data); value should be <33ms for real-time
    delay=32

    # This `host` should be changed accordingly; i.e. host of the target RTSP Server
    #host=192.168.1.250
    #host=140.113.86.92
    host=10.194.188.106

    # This is the path where the expected output URL for output video stream with PiH BBox
    path=output-ee

    # If Enabled (is_forced_plot=0), it will take the latest BBox and plot them into the current frame
    # This is still BUG, please disable it for now!
    is_forced_plot=0

    # If this parameter is enabled (is_raw=1), this Visualizer will only show real Video Stream (simply forward)
    is_raw=0

    # There are two type of `mode`: `rtsp` (default) and `opencv`
    mode=rtsp

    # This parameters
    window_width=1920
    window_height=1080

    [stream:gps]
    mode=online
