# Detection
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-deploy-3
  labels:
    name: detection-deploy-3
  namespace: eagleeye
spec:
  replicas: 1
  selector:
    matchLabels:
      name: detection-deploy-3
  template:
    metadata:
      name: detection-deploy-3
      labels:
        name: detection-deploy-3
#      annotations:
#        k8s.v1.cni.cncf.io/networks: '[
#          {
#            "name": "data-net-app",
#            "namespace": "mec-app",
#            "ips": [ "10.194.188.115/24" ]
#          }
#        ]'
    spec:
      volumes:
        - name: detection-config
          configMap:
            name: detection-configmap
            items:
            - key: "detection.conf"
              path: "detection.conf"
            - key: "site.conf"
              path: "site.conf"
        - name: config-files
          persistentVolumeClaim:
            claimName: detection-config-volume-claim-3
      containers:
        - name: detection-deploy-3
          image: timwilliam/eagleeye.detection:2.4
          #image: 5g-dive/eagleeye/dual-object-detection-service:1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: detection-config
              mountPath: "/conf/dual-det"
              readOnly: false
            - name: config-files
              mountPath: "/app/config_files"
      imagePullSecrets:
        - name: timwilliam-regcred
      restartPolicy: Always
