# EWS Node Port (API to EWS)
apiVersion: v1
kind: Service
metadata:
  name: ews-service
spec:
  type: NodePort
  selector:
    name: ews-deploy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000