---
# EWS-test deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ews-deploy-test
  namespace: eagleeye
  labels:
    name: ews-deploy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ews-deploy-test
  template:
    metadata:
      name: ews-deploy-test
      labels:
        name: ews-deploy-test
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "data-net-app",
            "namespace": "mec-app",
            "ips": [ "10.194.188.119/24" ]
          }
        ]'
    spec:
      volumes:
        - name: ews-config
          configMap:
            name: ews-configmap
            items:
            - key: "ews.conf"
              path: "ews.conf"
            - key: "site.conf"
              path: "site.conf"
        - name: ews-dual-det-config
          configMap:
            name: ews-dual-det-configmap
            items:
            - key: "site.conf"
              path: "site.conf"
      containers:
        - name: ews 
          image: timwilliam/eagleeye.webservice:2.3
          #image: 5g-dive/eagleeye/web-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ews-config
              mountPath: "/conf/ews"
              readOnly: false
            - name: ews-dual-det-config
              mountPath: "/conf/dual-det"
              readOnly: false
      imagePullSecrets:
        - name: timwilliam-regcred
...
---
# EWS-test Service
apiVersion: v1
kind: Service
metadata:
  name: ews-ext-service-test
  namespace: eagleeye
spec:
  type: NodePort
  selector:
    name: ews-deploy-test
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31111

