# EWS Node Port (API to EWS)
apiVersion: v1
kind: Service
metadata:
  name: detection-service
  namespace: eagleeye
spec:
  selector:
    name: detection-deploy
  ports:
  - port: 5551
    targetPort: 5551
