# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: eagleeye
spec:
  selector:
    name: redis-deploy
    #externalIPs:
    #- 10.194.188.110
  ports:
  - port: 6379
    targetPort: 6379
