# Scheduler Streaming Service
apiVersion: v1
kind: Service
metadata:
  name: scheduler-stream-service
  namespace: eagleeye
spec:
  ports:
    - name: rtsp
      protocol: TCP
      port: 554
      targetPort: 554
  externalIPs:
    - 140.113.86.92
