# Scheduler Streaming Service
apiVersion: v1
kind: Service
metadata:
  name: scheduler-stream-service
spec:
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
  externalIPs:
    - 140.113.86.92