apiVersion: v1
kind: Service
metadata:
  name: scheduler-ext-service
  namespace: eagleeye
spec:
  type: NodePort
  selector:
    name: scheduler-deploy
  ports:
  - port: 5550
    targetPort: 5550
    nodePort: 31200
