# Scheduler Service
apiVersion: v1
kind: Service
metadata:
  name: visualizer-service
  namespace: eagleeye
spec:
  type: NodePort
  selector:
    name: visualizer-deploy
  ports:
  - port: 5548
    targetPort: 5548
    nodePort: 32000
