# Scheduler Service
apiVersion: v1
kind: Service
metadata:
  name: visualizer-raw-service
  namespace: eagleeye
spec:
  type: NodePort
  selector:
    name: visualizer-deploy-raw
  ports:
  - port: 5547
    targetPort: 5547
    nodePort: 32010
