# Detection
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detection-deploy
  template:
    metadata:
      labels:
        app: detection-deploy
    spec:
      containers:
        - name: detection-deploy
          image: timwilliam/eagleeye.detection:1.0
          #image: 5g-dive/eagleeye/dual-object-detection-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5551
          volumeMounts:
            - name: detection-config
              mountPath: "/conf/dual-det"
              readOnly: false
            - name: detection-config-files
              mountPath: /app/config_files
      volumes:
        - name: detection-config
          configMap:
            name: detection-configmap
            items:
            - key: "detection.conf"
              path: "detection.conf"
            - key: "site.conf"
              path: "site.conf"
        - name: config-files
          persistentVolumeClaim:
            claimName: detection-config-files
      restartPolicy: Always