apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: detection-deploy-2
  name: detection-deploy-2
  namespace: eagleeye
spec:
  replicas: 1
  selector:
    matchLabels:
      name: detection-deploy-2
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "data-net-app", "namespace": "mec-app",
          "ips": [ "10.194.188.114/24" ] } ]'
      labels:
        name: detection-deploy-2
      name: detection-deploy-2
    spec:
      containers:
      - image: timwilliam/eagleeye.detection:2.3
        imagePullPolicy: IfNotPresent
        name: detection-deploy-2
        volumeMounts:
        - mountPath: /conf/dual-det
          name: detection-config
          readOnly: false
        - mountPath: /app/config_files
          name: config-files
      imagePullSecrets:
      - name: timwilliam-regcred
      restartPolicy: Always
      volumes:
      - configMap:
          items:
          - key: detection.conf
            path: detection.conf
          - key: site.conf
            path: site.conf
          name: detection-configmap
        name: detection-config
      - name: config-files
        persistentVolumeClaim:
          claimName: detection-config-volume-claim-2
