apiVersion: v1
kind: PersistentVolume
metadata:
  name: detection-config-volume
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/s010132/devel/eagleeye/object-detection-service/config_files