apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: detection-config-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: "detection-config-files"