apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo-deploy
  name: mongo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-deploy
  template:
    metadata:
      labels:
        name: mongo-deploy
      name: mongo-deploy
    spec:
      containers:
      - image: mongo:4.4.0
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-volume
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-volume-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  hostPath:
    path: /home/s010132/devel/eagleeye_tim/orchestration-imec/db-dir/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
