apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo-deploy
  name: mongo-deploy
  namespace: eagleeye
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-deploy
  template:
    metadata:
      labels:
        name: mongo-deploy
      name: mongo-deploy
    spec:
      containers:
      - image: mongo:4.4.0
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-volume
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-volume-claim
