apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis-deploy
  name: redis-deploy
  namespace: eagleeye
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-deploy
  template:
    metadata:
      labels:
        name: redis-deploy
      name: redis-deploy
    spec:
      containers:
      - image: timwilliam/eagleeye.redis:1.0
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-volume
      imagePullSecrets:
      - name: timwilliam-regcred
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: redis-volume-claim
