# Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-deploy
  template:
    metadata:
      name: redis-deploy
      labels:
        name: redis-deploy
    spec:
      volumes:
        - name: redis
          hostPath:
            # Update this hostPath setting as necessary !
            path: /home/s010132/devel/eagleeye_tim/orchestration-imec/db-dir/redis
      containers:
        - name: redis
          image: timwilliam/eagleeye.redis:1.0
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis
              #lifecycle:
              #postStart:
              #exec:
              #command: ["redis-server", "--appendonly", "yes", "--requirepass", "bismillah"]