apiVersion: v1
kind: Service
metadata:
  name: detection-service
spec:
  ports:
  - port: 5551
    targetPort: 5551
  selector:
    name: detection-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: ews-ext-service
spec:
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
  selector:
    name: ews-deploy
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ews-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: ews-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  ports:
  - port: 5551
    targetPort: 5551
  selector:
    name: scheduler-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-stream-service
spec:
  externalIPs:
  - 140.113.86.92
  ports:
  - name: rtmp
    port: 1935
    protocol: TCP
    targetPort: 1935
