apiVersion: v1
kind: Service
metadata:
  name: ews-ext-service
  namespace: eagleeye
spec:
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
  selector:
    name: ews-deploy
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ews-service
  namespace: eagleeye
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: ews-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: eagleeye
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: eagleeye
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-ext-service
  namespace: eagleeye
spec:
  ports:
  - nodePort: 32000
    port: 5549
    targetPort: 5549
  selector:
    name: scheduler-deploy
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: eagleeye
spec:
  ports:
  - name: visualizer
    port: 5550
    targetPort: 5550
  - name: worker-1
    port: 5551
    targetPort: 5551
  - name: worker-2
    port: 5552
    targetPort: 5552
  - name: worker-3
    port: 5553
    targetPort: 5553
  selector:
    name: scheduler-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: visualizer-service-raw
  namespace: eagleeye
spec:
  ports:
  - nodePort: 31400
    port: 5547
    targetPort: 5547
  selector:
    name: visualizer-deploy-raw
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: visualizer-service
  namespace: eagleeye
spec:
  ports:
  - nodePort: 31500
    port: 5548
    targetPort: 5548
  selector:
    name: visualizer-deploy
  type: NodePort
