apiVersion: v1
kind: Service
metadata:
  name: ews-ext-service
  namespace: eagleeye
spec:
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
  selector:
    name: ews-deploy
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ews-service
  namespace: eagleeye
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: ews-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: eagleeye
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: eagleeye
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: eagleeye
spec:
  ports:
  - name: visualizer
    port: 5550
    targetPort: 5550
  - name: worker-1
    port: 5551
    targetPort: 5551
  - name: worker-2
    port: 5552
    targetPort: 5552
  - name: worker-3
    port: 5553
    targetPort: 5553
  selector:
    name: scheduler-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-stream-service
  namespace: eagleeye
spec:
  externalIPs:
  - 140.113.86.92
  ports:
  - name: rtsp
    port: 554
    protocol: TCP
    targetPort: 554
