apiVersion: v1
kind: PersistentVolume
metadata:
  name: detection-config-volume
  namespace: eagleeye
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 4Gi
  hostPath:
    path: /home/s010132/devel/eagleeye/object-detection-service/config_files
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  namespace: eagleeye
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  hostPath:
    path: /home/s010132/devel/eagleeye_tim/orchestration-imec/db-dir/mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  namespace: eagleeye
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  hostPath:
    path: /home/s010132/devel/eagleeye_tim/orchestration-imec/db-dir/redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scheduler-volume
  namespace: eagleeye
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/s010132/devel/eagleeye/data
