FROM        ubuntu:trusty
MAINTAINER  Muhammad Febrian Ardiansyah <ardihikaru3@gmail.com>

ENV         DEBIAN_FRONTEND=noninteractive

RUN         printf "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d
RUN         apt-get update && apt-get install -y redis-server

EXPOSE      6379
ENTRYPOINT  ["/usr/bin/redis-server"]
