FROM        redis:5.0.5-alpine3.9
MAINTAINER  Muhammad Febrian Ardiansyah <ardihikaru3@gmail.com>

#ENV         DEBIAN_FRONTEND=noninteractive

#RUN         printf "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d
#RUN         apk update && apk add redis-server

#EXPOSE      6379
#ENTRYPOINT  ["/usr/bin/redis-server"]
