# Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: eagleeye
  labels:
    name: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-deploy
  template:
    metadata:
      name: redis-deploy
      labels:
        name: redis-deploy
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "data-net-app",
            "namespace": "mec-app",
            "ips": [ "10.194.188.110/24" ]
          }
        ]'
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-volume-claim
      containers:
        - name: redis
          image: timwilliam/eagleeye.redis:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-volume
              mountPath: /data
      imagePullSecrets:
        - name: timwilliam-regcred
