apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: detection-config-volume-claim-2
  namespace: eagleeye
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
