apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scheduler-volume-claim
  namespace: eagleeye
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
