apiVersion: v1
kind: PersistentVolume
metadata:
  name: detection-config-volume
  namespace: eagleeye
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadOnlyMany
      #persistentVolumeReclaimPolicy: Recycle
  hostPath:
      #path: /home/k200/nctuAPP/20201028-eagleeye/deployment/config_files
          path: /home/s010132/devel/eagleeye/object-detection-service/config_files
