apiVersion: v1
kind: PersistentVolume
metadata:
  name: detection-config-volume-2
  namespace: eagleeye
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadOnlyMany
      #persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/s010132/devel/eagleeye/object-detection-service/config_files

