apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
      #persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/s010132/devel/eagleeye_tim/orchestration-imec/db-dir/mongo

