apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  namespace: eagleeye
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
      #persistentVolumeReclaimPolicy: Recycle
  hostPath:
      #path: /home/s010132/devel/eagleeye_tim/orchestration-imec/db-dir/redis
    path: /home/s010132/devel/eagleeye_k8s/orchestration-gpu/db-dir/redis
