apiVersion: v1
kind: PersistentVolume
metadata:
  name: scheduler-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
      #persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/s010132/devel/eagleeye/data

