apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - scheduler-configmap.yaml
  - scheduler-persistent-volume.yaml
  - scheduler-persistent-volume-claim.yaml
  - scheduler-service.yaml
  - scheduler-stream-service.yaml
  - scheduler-deployment.yaml
