# Scheduler
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer-deploy-raw
  namespace: eagleeye
  labels:
    name: visualizer-deploy-raw
spec:
  replicas: 1
  selector:
    matchLabels:
      name: visualizer-deploy-raw
  template:
    metadata:
      name: visualizer-deploy-raw
      labels:
        name: visualizer-deploy-raw
    spec:
      volumes:
        - name: visualizer-config-raw
          configMap:
            name: visualizer-configmap-raw
            items:
            - key: "visualizer.conf"
              path: "visualizer.conf"
            - key: "site.conf"
              path: "site.conf"
      containers:
        - name: visualizer-deploy-raw
          #image: 5g-dive/eagleeye/scheduler-service:1.0
          image: timwilliam/eagleeye.visualizer:2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 554
          volumeMounts:
            - name: visualizer-config-raw
              mountPath: "/conf/visualizer"
              readOnly: false
      imagePullSecrets:
        - name: timwilliam-regcred
