# How to build: docker build -f Dockerfile-parent -t 5g-dive/eagleeye/dual-object-detection-service-head:2.2 .

# Misc:
# Install Docker Nvidia 2.0: https://cnvrg.io/how-to-setup-docker-and-nvidia-docker-2-0-on-ubuntu-18-04/

FROM 5g-dive/eagleeye/nvidia-gpu-opencv:2.2
MAINTAINER NCTU Team (mfardiansyah.eed08g@nctu.edu.tw)

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

COPY requirements-no-cv.txt /tmp/requirements.txt

# install other requirements
RUN pip3 install Cython

RUN pip3 install -r /tmp/requirements.txt

